const actionTypes = {
  USER_LOG: 'USER_LOG',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  USER_LOG: 'USER_LOG',
  USER_ID: 'USER_ID',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  BYE_CART: 'BYE_CART',
  Admin: 'Admin',
  CREATE_PAYMENT_ID: 'CREATE_PAYMENT_ID',
  GET_PAYMENT_VALUE: 'GET_PAYMENT_VALUE',
  CREATE_ORDER_PAID_ID: 'CREATE_ORDER_PAID_ID',
};
export default actionTypes;
